apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginPanGu
spec:
  enabled: true
  version: 1.0.0
  requires: "*"
  author:
    name: liuzhihang
    website: https://github.com/liuzhihang
  logo: https://halo.run/logo
  settingName: plugin-pangu-settings
  configMapName: plugin-pangu-configMap
  homepage: https://github.com/liuzhihang/plugin-pangu
  displayName: "pangu"
  description: "中英文、符号之间自动添加空格"
  license:
    - name: "MIT"
